// <auto-generated />
using System;
using DartSmart.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DartSmart.Infrastructure.Migrations
{
    [DbContext(typeof(DartSmartDbContext))]
    [Migration("20260111193514_AddBotSupport")]
    partial class AddBotSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DartSmart.Domain.Entities.DartThrow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DartNumber")
                        .HasColumnType("integer")
                        .HasColumnName("dart_number");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsBust")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bust");

                    b.Property<int>("Multiplier")
                        .HasColumnType("integer")
                        .HasColumnName("multiplier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("Round")
                        .HasColumnType("integer")
                        .HasColumnName("round");

                    b.Property<int>("Segment")
                        .HasColumnType("integer")
                        .HasColumnName("segment");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("dart_throws", (string)null);
                });

            modelBuilder.Entity("DartSmart.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_player_index");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer")
                        .HasColumnName("current_round");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_type");

                    b.Property<string>("InMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("in_mode");

                    b.Property<string>("OutMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("out_mode");

                    b.Property<int>("StartScore")
                        .HasColumnType("integer")
                        .HasColumnName("start_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_id");

                    b.HasKey("Id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("DartSmart.Domain.Entities.GamePlayer", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("CurrentScore")
                        .HasColumnType("integer")
                        .HasColumnName("current_score");

                    b.Property<int>("DartsThrown")
                        .HasColumnType("integer")
                        .HasColumnName("darts_thrown");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("LegsWon")
                        .HasColumnType("integer")
                        .HasColumnName("legs_won");

                    b.Property<int>("SetsWon")
                        .HasColumnType("integer")
                        .HasColumnName("sets_won");

                    b.Property<int>("TurnOrder")
                        .HasColumnType("integer")
                        .HasColumnName("turn_order");

                    b.HasKey("GameId", "PlayerId");

                    b.ToTable("game_players", (string)null);
                });

            modelBuilder.Entity("DartSmart.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BotSkillLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("DartSmart.Domain.Entities.DartThrow", b =>
                {
                    b.HasOne("DartSmart.Domain.Entities.Game", null)
                        .WithMany("Throws")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DartSmart.Domain.Entities.GamePlayer", b =>
                {
                    b.HasOne("DartSmart.Domain.Entities.Game", null)
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DartSmart.Domain.Entities.Player", b =>
                {
                    b.OwnsOne("DartSmart.Domain.ValueObjects.PlayerStatistics", "Statistics", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Best3DartScore")
                                .HasColumnType("integer")
                                .HasColumnName("best_3_dart_score");

                            b1.Property<int>("Count180s")
                                .HasColumnType("integer")
                                .HasColumnName("count_180s");

                            b1.Property<int>("HighestCheckout")
                                .HasColumnType("integer")
                                .HasColumnName("highest_checkout");

                            b1.Property<int>("TotalDarts")
                                .HasColumnType("integer")
                                .HasColumnName("total_darts");

                            b1.Property<int>("TotalGames")
                                .HasColumnType("integer")
                                .HasColumnName("total_games");

                            b1.Property<int>("TotalPoints")
                                .HasColumnType("integer")
                                .HasColumnName("total_points");

                            b1.Property<int>("Wins")
                                .HasColumnType("integer")
                                .HasColumnName("wins");

                            b1.HasKey("PlayerId");

                            b1.ToTable("players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("Statistics")
                        .IsRequired();
                });

            modelBuilder.Entity("DartSmart.Domain.Entities.Game", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Throws");
                });
#pragma warning restore 612, 618
        }
    }
}
